# Generated by Django 5.0.7 on 2024-09-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipta',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
