# Generated by Django 5.1.1 on 2024-09-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band_qilish',
            options={'verbose_name_plural': 'Band_qilishlar'},
        ),
        migrations.AlterModelOptions(
            name='chipta',
            options={'verbose_name_plural': 'Chiptalar'},
        ),
        migrations.AlterModelOptions(
            name='yolovchi',
            options={'verbose_name_plural': 'Yolovchilar'},
        ),
    ]
