# Generated by Django 5.1.1 on 2024-09-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0002_chipta_is_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipta',
            name='raqam',
            field=models.BigIntegerField(unique=True),
        ),
    ]
