# Generated by Django 5.1.1 on 2024-09-10 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0002_alter_band_qilish_options_alter_chipta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band_qilish',
            name='yolovchi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chipta.yolovchi'),
        ),
        migrations.AlterField(
            model_name='chipta',
            name='raqam',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
