# Generated by Django 5.1.1 on 2024-09-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0003_alter_band_qilish_yolovchi_alter_chipta_raqam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipta',
            name='raqam',
            field=models.PositiveBigIntegerField(auto_created=True, unique=True),
        ),
    ]
