# Generated by Django 5.1.1 on 2024-09-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0004_alter_chipta_raqam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipta',
            name='raqam',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
