# Generated by Django 5.1.1 on 2024-09-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0005_alter_chipta_raqam'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipta',
            name='soni',
            field=models.IntegerField(default=47),
            preserve_default=False,
        ),
    ]
