# Generated by Django 5.1.1 on 2024-09-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0006_chipta_soni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yolovchi',
            options={'verbose_name_plural': "Yo'lovchilar"},
        ),
    ]
