# Generated by Django 5.1.1 on 2024-09-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0008_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band_qilish',
            name='chipta',
        ),
        migrations.RemoveField(
            model_name='band_qilish',
            name='yolovchi',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Chipta',
        ),
        migrations.DeleteModel(
            name='Band_qilish',
        ),
        migrations.DeleteModel(
            name='Yolovchi',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
