# Generated by Django 5.1.1 on 2024-09-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chipta', '0009_remove_band_qilish_chipta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chipta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.PositiveBigIntegerField(unique=True)),
                ('kompaniya', models.CharField(max_length=200)),
                ('ketish_vaqti', models.DateTimeField()),
                ('kelish_vaqti', models.DateTimeField()),
                ('qaysi_shaharga', models.CharField(max_length=200)),
                ('qaysi_shahardan', models.CharField(max_length=200)),
                ('soni', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Chiptalar',
            },
        ),
        migrations.CreateModel(
            name='Yolovchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=200)),
                ('sharifi', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('telefon', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': "Yo'lovchilar",
            },
        ),
        migrations.CreateModel(
            name='Band_qilish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chipta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chipta.chipta')),
                ('yolovchi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chipta.yolovchi')),
            ],
            options={
                'verbose_name_plural': 'Band_qilishlar',
            },
        ),
    ]
