# Generated by Django 5.1.1 on 2024-09-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0011_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
