# Generated by Django 5.0.7 on 2024-09-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0013_alter_chipta_raqam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipta',
            name='raqam',
            field=models.IntegerField(unique=True),
        ),
    ]
