# Generated by Django 5.0.7 on 2024-09-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0014_alter_chipta_raqam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yolovchi',
            name='ismi',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
